### ISSUE TITLE
autogen-support.sh is missing

### ISSUE THREAD

**Issue by wom-bat** [rashack/guile-zeromq-3#1]
I clone the reporitory then do
   ./autogen.sh
and see
  ./autogen.sh: line 31: ./autogen-support.sh: No such file or directory

**Comment by rashack** [comment]
Hi,

Sorry for the inconvenience, you should do `autoreconf -i` instead of `./autogen.sh`.
I updated the HACKING file.

Thanks for pointing out the problem, let me know if there is anything else that's broken.
